### ISSUE TITLE
Be able to have total count and pagination on some requests

### ISSUE THREAD

**Issue by Ikaer** [ppy/osu-api#103]
Hi everyone and Peppy!

Just a few suggestions:
- For requests like "/api/get_user_best", "/api/get_user_recent", It would be nice to have the total count of possible results and then be able to get chunks of them with pagination (in that way, request results are not too heavy, but we are able to get all the data).
  For example, The only work around I figured to get all the beatmaps a player has play is to use /api/get_scores with a specified user and a specified beatmap which requires to browse all beatmap ids for one player :(. It would be more easy to be able to get all play history with "/api/get_user_recent" but paginated in order to avoid heavy requests.
- /api/get_beatmaps could use such an evolution too. Actually the only way to get all beatmap data, is to use "since", and fetch all months for example.
- Last thing, I'm not sure if it is normal, but every time I request /api/get_beatmaps without "since" parameters, I only get beatmaps with -1 or -2 approved status, but If I had since=today for example, I get another approved status. I Imagine that the order is approved date for the last example, and something else for the request without the since. Wouldn't be better to have the same sort in both case, or maybe be to be able to precise the order.

Bye and thanks!

**Comment by peppy** [comment]
* Pagination is unreliable and prone to error (new beatmaps could be released while you are paginating results). The "since" parameter is an amicable solution to this.
* It's no less "heavy" to retrieve 1000 results as opposed to retrieving 950-1000. What would be most efficient is if you cache the content locally in your application so you have future data available when the user requests it.
* Retrieval of all beatmaps (using since, for example) is only supported currently for approved maps, which is why the approved restriction is in place. For the time being I don't see this changing.

**Comment by Ikaer** [comment]
- Ok, so pagination, bad idea, I get it :)
- I currently store results in my own database, so as you say, It works, but I have to repeatedly crawl your API to be sure to have no gap with your database. 
For example, let's take "/api/get_user_recent", if I call it, let's say once per day and I store the results, How can I be sure that between 2 calls, some user plays that I've not store yet will not be after the 50th record ?
- For the approved filter with since parameter, in fact, that's ok, I prefer it that way, I was just wondering why requests without the since parameter was never returning approved beatmaps.

**Comment by peppy** [comment]
We've changed the pagination method on the new osu-web api. It now returns a cursor which can be used for the next request. This won't be backported to osu-api (v1) though.
