### ISSUE TITLE
Be able to get multiple specific maps with /get_beatmaps

### ISSUE THREAD

**Issue by Igoorx** [ppy/osu-api#107]
Example of what i'm saying: /get_beatmaps?b=41442,14232,132345,231564
will return a JSON list containing these beatmaps.

This also can be made for all others pages (like /get_user), I think it would be useful.

**Comment by TheHowl** [comment]
This would just reduce the load of request, not the database load, as it 
would consist in making two different queries. Therefore, I think this 
is not going to happen.

**Comment by Igoorx** [comment]
Suppose I want to get information from a large number of beatmaps (or users) for example: 30, in the shortest possible time, I do not think it would be cool send 30 requests for it..

**Comment by omkelderman** [comment]
> I do not think it would be cool send 30 requests for it..

Actually it is (afaik) as long as you dont do them like continuous 24/7

**Comment by hypereddie** [comment]
> This would just reduce the load of request, not the database load, as it would consist in making two different queries.

Yes, but it would reduce the load because only 2 queries needs to be made for x amount of beatmaps, rather than having to do x queries for x amount of beatmaps

If I have to do 30 requests for 30 beatmaps, wouldn't that result in 30 queries on the database ?
If I could do 1 request for 30 beatmaps, and if what you said is correct, then only 2 queries would be made on the database.

**Comment by peppy** [comment]
database load would not change perceivably. only difference would be the number of requests you make.

besides, don't worry about the server load. that's my problem. if you are running out of requests per minute (hitting the api limit) then you should be asking for changes.

**Comment by Igoorx** [comment]
Oh, so ok, i will close this issue.
