### ISSUE TITLE
Add pack id and/or tag to /get_beatmaps

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-api#216]
alternatively, add a list of beatmap ids to /get_packs 

currently there's no way to associate beatmaps to their beatmap packs using the api alone

**Comment by LtLi0n** [comment]
What do you mean? Just download all of them and look through each one. Since it's only one call anyway, why would this be an issue?

**Comment by cl8n** [comment]
I don't want to download all of the packs, I just want to know which beatmaps are inside of each one

**Comment by LtLi0n** [comment]
But that does exactly that unless you are really concerned about those added 5kb or whatever with today's internet speeds...

**Comment by cl8n** [comment]
5kb? are we talking about the same thing? the latest osu! standard beatmap pack alone is 200mb

if you are suggesting to scrape the beatmap pack listing page, you're not supposed to do that... the relevant info could just be added to the public-facing api instead.

regardless of the use case I think the pack id/tag is data that should be included with every map

**Comment by LtLi0n** [comment]
Oh, my bad. Forgot that a beatmap pack is a separate format from a beatmapset and I assumed you are referring to beatmapsets.
Now I understand the issue you are having...

The easiest way to do it without an API is to scrap the names of a pack from the website since everything is in an incremental order.

You can actually do it through the API too if you know when the beatmap pack **before the beatmap pack you want** was published.
/api/get_beatmaps has **since** property so you can just grab **17** _because it looks like every single beatmap pack contains exactly 17_ maps which should be of the next beatmap pack.

Sorry for misleading earlier, morning tends to derp me up a lot 😄.

**Comment by jxu** [comment]
That relies on a lot of assumptions about beatmap packs.

**Comment by cl8n** [comment]
bump cuz it would probably be useful for management purposes stated in https://github.com/ppy/osu-web/issues/5444

**Comment by peppy** [comment]
I've tentatively added this but not sure how it will affect load. May be removed in the future if it becomes an issue. Please update documentation for `packs`.
