### ISSUE TITLE
More than 100 get_user_best

### ISSUE THREAD

**Issue by jxu** [ppy/osu-api#285]
Useful API tools like https://newpp.stanr.info/ need more than 100 top scores to be more accurate.

**Comment by peppy** [comment]
This version of the API is feature locked. Also due to our current infrastructure, returning more than 100 will cause issues. The eventual plan is to expand this further, but I can't guarantee when that will happen.

see [osu-web](https://github.com/ppy/osu-web) for the newer version of the api (https://docs.ppy.sh)
